### PR TITLE
Pauli to dense, matrix division and tests added.

### PR DESCRIPTION
**Pull request by amitjamadagni**
From the #34 converting pauli to dense using full.
Matrix division support added for A*X == B where A & B are`AbstractQuMatrix` & `AbstractQuMatrix` and A & B are `AbstractQuMatrix` and `AbstarctQuMatrix`.
Tests added.

### CODE REVIEW

**Comment by acroy** [comment]
Looks good to me.

**Comment by jrevels** [comment]
Looks good to me as well! Ready to merge?

**Comment by acroy** [comment]
Sure, go ahead.

Just as an info: we decided making `sigma*` dense, because the sparse format introduces quite some memory overhead for those small matrices and they are actually not really sparse (2 of 4 elements nonzero).

**Comment by jrevels** [comment]
Makes sense! Hopefully fixed-size matrices will become a thing sometime soon...

**Comment by acroy** [comment]
That would be really awesome!

**Comment by amitjamadagni** [comment]
:+1 that was fast :)

**Pull request merged**
