### PR TITLE
Resolve issue with new Tuple syntax in LabelBasis.

### PR DESCRIPTION
**Pull request by acroy**
This is an attempt to resolve the Travis failure for julia 0.4 by using the Compat package and new Tuple syntax.

### CODE REVIEW

**Comment by acroy** [comment]
Has anyone an idea what goes wrong? It's probably something trivial, but I can't figure it out ...

**Comment by acroy** [comment]
Ok, my original problem was somehow related to my editor not inserting the right kind of line break (or me being to stupid). Anyways, Travis works again, but there are tons of warnings. I am not sure if we want to address them now or wait until 0.4 has stabilized? But this should be a separate PR ...

**Comment by jrevels** [comment]
Awesome job, thanks for figuring this out! Sorry about not lending a hand - I was busy with QuDirac stuff yesterday.

**Comment by acroy** [comment]
@jrevels No problem; the hardest part was figuring out the missing new line character :-) What shall we do about the warnings?

**Pull request merged**
